# DevSecOps Workflow Definition
# This workflow is triggered on every push to the repository
name: DevGuard Workflow

on:
  push:
 
jobs:
  devguard-scanner:
    uses: l3montree-dev/devguard-action/.github/workflows/full.yml@main
    with:
        asset-name: "l3montree-cybersecurity/projects/devguard/assets/devguard-web"
    secrets:
        devguard-token: ${{ secrets.DEVGUARD_TOKEN }} 
        build-args: "--context=. --dockerfile=Dockerfile --build-arg=DEVGUARD_API_URL=https://api.main.devguard.org"